const fs = require('fs');
const path = require('path');

fs.mkdirSync('src/screens', { recursive: true });

const homeScreen = [
  "import React, { useState, useCallback } from 'react';",
  "import { View, Text, FlatList, TouchableOpacity, ActivityIndicator, StyleSheet } from 'react-native';",
  "import { useFocusEffect } from '@react-navigation/native';",
  "",
  "export default function HomeScreen({ route, navigation }) {",
  "  const { nome, cnpj } = route.params;",
  "  const [garantias, setGarantias] = useState([]);",
  "  const [loading, setLoading] = useState(true);",
  "",
  "  const fetchGarantias = async () => {",
  "    setLoading(true);",
  "    try {",
  "      const res = await fetch('http://192.168.1.3:3000/api/garantias?cnpj=' + cnpj);",
  "      const data = await res.json();",
  "      setGarantias(data);",
  "    } catch (e) {",
  "      console.log('Erro:', e);",
  "    } finally {",
  "      setLoading(false);",
  "    }",
  "  };",
  "",
  "  useFocusEffect(useCallback(() => { fetchGarantias(); }, [cnpj]));",
  "",
  "  return (",
  "    <View style={styles.container}>",
  "      <View style={styles.header}>",
  "        <Text style={styles.nomeCliente}>{nome}</Text>",
  "        <Text style={styles.cnpjCliente}>CNPJ: {cnpj}</Text>",
  "      </View>",
  "      <TouchableOpacity style={styles.btnNova} onPress={() => navigation.navigate('CriarGarantia', { cnpj }) }>",
  "        <Text style={styles.btnText}>NOVA GARANTIA</Text>",
  "      </TouchableOpacity>",
  "      {loading ? (",
  "        <ActivityIndicator size=\"large\" color=\"#007AFF\" />",
  "      ) : (",
  "        <FlatList",
  "          data={garantias}",
  "          keyExtractor={(item, index) => index.toString()}",
  "          renderItem={({ item }) => (",
  "            <View style={styles.card}>",
  "              <Text style={styles.label}>Protocolo: <Text style={styles.value}>{item.PROTOCOLO}</Text></Text>",
  "              <Text style={styles.label}>Produto: <Text style={styles.value}>{item.PRODUTO}</Text></Text>",
  "              <Text style={styles.label}>Tipo: <Text style={styles.value}>{item.TIPO}</Text></Text>",
  "              <Text style={styles.label}>Defeito: <Text style={styles.value}>{item.DEFEITO}</Text></Text>",
  "              <Text style={styles.label}>Status: <Text style={styles.value}>{item.STATUS}</Text></Text>",
  "              <Text style={styles.label}>Data: <Text style={styles.value}>{item.DATA_ABERTURA}</Text></Text>",
  "            </View>",
  "          )}",
  "          ListEmptyComponent={<Text style={styles.empty}>Nenhuma garantia encontrada</Text>}",
  "        />",
  "      )}",
  "    </View>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  container: { flex: 1, padding: 16, backgroundColor: '#f5f5f5' },",
  "  header: { marginBottom: 20, padding: 15, backgroundColor: '#fff', borderRadius: 10, elevation: 2 },",
  "  nomeCliente: { fontSize: 18, fontWeight: 'bold', color: '#007AFF' },",
  "  cnpjCliente: { fontSize: 14, color: '#888', marginTop: 4 },",
  "  btnNova: { backgroundColor: '#007AFF', padding: 15, borderRadius: 8, alignItems: 'center', marginBottom: 20 },",
  "  btnText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },",
  "  card: { backgroundColor: '#fff', padding: 15, borderRadius: 10, marginBottom: 10, elevation: 3 },",
  "  label: { fontWeight: 'bold', color: '#333', marginBottom: 4 },",
  "  value: { fontWeight: 'normal', color: '#555' },",
  "  empty: { textAlign: 'center', marginTop: 50, color: '#999', fontSize: 16 }",
  "});"
].join('\n');

const criarGarantiaScreen = [
  "import React, { useState, useEffect } from 'react';",
  "import { View, Text, TextInput, TouchableOpacity, ScrollView, StyleSheet, Alert, Modal, FlatList } from 'react-native';",
  "",
  "const API = 'http://192.168.1.3:3000/api';",
  "",
  "export default function CriarGarantiaScreen({ route, navigation }) {",
  "  const { cnpj } = route.params;",
  "  const [listas, setListas] = useState({ Tipo: [], Defeito: [], Envio: [], Suporte: [] });",
  "  const [produtoBusca, setProdutoBusca] = useState('');",
  "  const [sugestoes, setSugestoes] = useState([]);",
  "  const [form, setForm] = useState({ produto: '', tipo: '', defeito: '', envio: '', suporte: '', nfe: '', obs: '' });",
  "  const [modal, setModal] = useState({ show: false, campo: '', opcoes: [] });",
  "",
  "  useEffect(() => {",
  "    fetch(API + '/listas')",
  "      .then(r => r.json())",
  "      .then(d => setListas(d))",
  "      .catch(() => Alert.alert('Erro', 'Falha ao carregar listas'));",
  "  }, []);",
  "",
  "  const buscarProduto = async (texto) => {",
  "    setProdutoBusca(texto);",
  "    if (texto.length >= 3) {",
  "      try {",
  "        const r = await fetch(API + '/produtos?busca=' + texto);",
  "        const d = await r.json();",
  "        setSugestoes(d);",
  "      } catch(e) { setSugestoes([]); }",
  "    } else {",
  "      setSugestoes([]);",
  "    }",
  "  };",
  "",
  "  const salvar = async () => {",
  "    if (!form.produto || !form.tipo || !form.defeito) {",
  "      return Alert.alert('Erro', 'Preencha Produto, Tipo e Defeito');",
  "    }",
  "    try {",
  "      const r = await fetch(API + '/garantias', {",
  "        method: 'POST',",
  "        headers: { 'Content-Type': 'application/json' },",
  "        body: JSON.stringify({ cnpj: cnpj, produto: form.produto, tipo: form.tipo, defeito: form.defeito, envio: form.envio, suporte: form.suporte, nfe: form.nfe, obs: form.obs, qte: 1, codigo: 1, solicitante: '', fone: '', email: '' })",
  "      });",
  "      if (r.ok) {",
  "        Alert.alert('Sucesso', 'Garantia criada!');",
  "        navigation.goBack();",
  "      } else {",
  "        Alert.alert('Erro', 'Falha ao salvar');",
  "      }",
  "    } catch(e) {",
  "      Alert.alert('Erro', 'Falha ao conectar');",
  "    }",
  "  };",
  "",
  "  const abrirModal = (campo) => {",
  "    const campoOriginal = campo.charAt(0).toUpperCase() + campo.slice(1);",
  "    setModal({ show: true, campo: campo.toLowerCase(), opcoes: listas[campoOriginal] || [] });",
  "  };",
  "",
  "  return (",
  "    <ScrollView style={styles.container}>",
  "      <Text style={styles.label}>Produto *</Text>",
  "      <TextInput style={styles.input} value={produtoBusca} onChangeText={buscarProduto} placeholder=\"Digite para buscar...\" />",
  "      {sugestoes.map(item => (",
  "        <TouchableOpacity key={item.PRODUTO} style={styles.sugestao} onPress={() => {",
  "          setForm({...form, produto: item.PRODUTO});",
  "          setProdutoBusca(item.DESCRICAO);",
  "          setSugestoes([]);",
  "        }}>",
  "          <Text style={styles.sugestaoText}>{item.DESCRICAO}</Text>",
  "        </TouchableOpacity>",
  "      ))}",
  "      {form.produto ? <Text style={styles.selecionado}>Codigo: {form.produto}</Text> : null}",
  "",
  "      <Text style={styles.label}>Tipo *</Text>",
  "      <TouchableOpacity style={styles.input} onPress={() => abrirModal('Tipo')}>",
  "        <Text>{form.tipo || 'Selecione...'}</Text>",
  "      </TouchableOpacity>",
  "",
  "      <Text style={styles.label}>Defeito *</Text>",
  "      <TouchableOpacity style={styles.input} onPress={() => abrirModal('Defeito')}>",
  "        <Text>{form.defeito || 'Selecione...'}</Text>",
  "      </TouchableOpacity>",
  "",
  "      <Text style={styles.label}>Suporte</Text>",
  "      <TouchableOpacity style={styles.input} onPress={() => abrirModal('Suporte')}>",
  "        <Text>{form.suporte || 'Selecione...'}</Text>",
  "      </TouchableOpacity>",
  "",
  "      <Text style={styles.label}>Envio</Text>",
  "      <TouchableOpacity style={styles.input} onPress={() => abrirModal('Envio')}>",
  "        <Text>{form.envio || 'Selecione...'}</Text>",
  "      </TouchableOpacity>",
  "",
  "      <Text style={styles.label}>NFE</Text>",
  "      <TextInput style={styles.input} value={form.nfe} onChangeText={v => setForm({...form, nfe: v})} placeholder=\"NFe...\" />",
  "",
  "      <Text style={styles.label}>Observacao</Text>",
  "      <TextInput style={[styles.input, {height: 80}]} multiline value={form.obs} onChangeText={v => setForm({...form, obs: v})} placeholder=\"Obs...\" />",
  "",
  "      <TouchableOpacity style={styles.btnSalvar} onPress={salvar}>",
  "        <Text style={styles.btnText}>SALVAR</Text>",
  "      </TouchableOpacity>",
  "",
  "      <Modal visible={modal.show} transparent animationType=\"slide\">",
  "        <View style={styles.modalBg}>",
  "          <View style={styles.modalContent}>",
  "            <Text style={styles.modalTitulo}>Selecione {modal.campo}</Text>",
  "            <FlatList",
  "              data={modal.opcoes}",
  "              keyExtractor={(item, i) => i.toString()}",
  "              renderItem={({ item }) => (",
  "                <TouchableOpacity style={styles.modalItem} onPress={() => {",
  "                  setForm({...form, [modal.campo]: item});",
  "                  setModal({ show: false, campo: '', opcoes: [] });",
  "                }}>",
  "                  <Text>{item}</Text>",
  "                </TouchableOpacity>",
  "              )}",
  "            />",
  "            <TouchableOpacity style={styles.btnFechar} onPress={() => setModal({ show: false, campo: '', opcoes: [] })}>",
  "              <Text style={{color: '#fff'}}>Fechar</Text>",
  "            </TouchableOpacity>",
  "          </View>",
  "        </View>",
  "      </Modal>",
  "    </ScrollView>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  container: { flex: 1, padding: 20, backgroundColor: '#fff' },",
  "  label: { fontWeight: 'bold', marginTop: 15, marginBottom: 5, color: '#333' },",
  "  input: { borderWidth: 1, borderColor: '#ccc', borderRadius: 6, padding: 12, backgroundColor: '#f9f9f9', fontSize: 15 },",
  "  sugestao: { padding: 12, backgroundColor: '#f0f0f0', borderBottomWidth: 1, borderColor: '#ddd' },",
  "  sugestaoText: { fontSize: 14 },",
  "  selecionado: { color: '#007AFF', fontWeight: 'bold', marginTop: 5 },",
  "  btnSalvar: { backgroundColor: '#007AFF', padding: 15, borderRadius: 8, alignItems: 'center', marginTop: 30, marginBottom: 40 },",
  "  btnText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },",
  "  modalBg: { flex: 1, justifyContent: 'center', backgroundColor: 'rgba(0,0,0,0.5)' },",
  "  modalContent: { margin: 20, backgroundColor: '#fff', borderRadius: 10, padding: 20, maxHeight: '70%' },",
  "  modalTitulo: { fontSize: 18, fontWeight: 'bold', marginBottom: 15, color: '#007AFF' },",
  "  modalItem: { padding: 15, borderBottomWidth: 1, borderColor: '#eee' },",
  "  btnFechar: { backgroundColor: '#999', padding: 12, borderRadius: 8, alignItems: 'center', marginTop: 15 }",
  "});"
].join('\n');

const appJs = [
  "import React from 'react';",
  "import { NavigationContainer } from '@react-navigation/native';",
  "import { createNativeStackNavigator } from '@react-navigation/native-stack';",
  "import LoginScreen from './src/screens/LoginScreen';",
  "import HomeScreen from './src/screens/HomeScreen';",
  "import CriarGarantiaScreen from './src/screens/CriarGarantiaScreen';",
  "",
  "const Stack = createNativeStackNavigator();",
  "",
  "export default function App() {",
  "  return (",
  "    <NavigationContainer>",
  "      <Stack.Navigator screenOptions={{ headerShown: false }}>",
  "        <Stack.Screen name=\"Login\" component={LoginScreen} />",
  "        <Stack.Screen name=\"Home\" component={HomeScreen} />",
  "        <Stack.Screen name=\"CriarGarantia\" component={CriarGarantiaScreen} />",
  "      </Stack.Navigator>",
  "    </NavigationContainer>",
  "  );",
  "}"
].join('\n');

fs.writeFileSync('src/screens/HomeScreen.js', homeScreen, 'utf8');
fs.writeFileSync('src/screens/CriarGarantiaScreen.js', criarGarantiaScreen, 'utf8');
fs.writeFileSync('App.js', appJs, 'utf8');

console.log('Arquivos criados com sucesso!');